### ISSUE TITLE
Problem trying to sign in after following the steps of Get Started page.

### ISSUE THREAD

**Issue by jac1013** [keystonejs/keystone#4241]
### Expected behavior
* I should be able to enter to http://localhost:3000/keystone/signin and see the signin view.

### Actual/Current behavior
* I get an error in the console that's related to ``signin.js`` file in keystone core library.
```JavaScript
signin.js:1275 Uncaught TypeError: $export is not a function
    at Object.90../_descriptors (signin.js:1275)
    at s (signin.js:1)
    at signin.js:1
    at Object.18.../../modules/_core (signin.js:128)
    at s (signin.js:1)
    at signin.js:1
    at Object.4.core-js/library/fn/object/define-property (signin.js:19)
    at s (signin.js:1)
    at signin.js:1
    at Object.59../_an-object (signin.js:820)
```

### Steps to reproduce the actual/current behavior
* I followed the Tutorial in the Getting Started page.
* I used all the defaults values in the yeoman generator part.

### Environment
* OS: Linux Mint 18.1.
* Browser: Chrome 57.0.2987.110 (64-bit)
* MongoDB is installed properly.
* No errors are shown in installation process (just the error I showed above which is in the browser).
* No errors are shown in the Node server.

| Software         | Version
| ---------------- | -------
| Keystone         | keystone@4.0.0-beta.5
| Node             |  5.11 / 7.4 (Without success in none of them).

**Comment by jac1013** [comment]
The problem was related to the version of node being used.

I think we need to specify somewhere in the documentation the Node version that we need to use in order for Keystone to work properly (for example I had problems with Node 7.4, and it worked in Node 4.3).

Just in case anyone get in the way of this issue.
