### PR TITLE
Fix `@keystone-6/fields-document` package breaking when compiling in SSR environments

### PR DESCRIPTION
**Pull request by marekryb**
This attempts to fix https://github.com/keystonejs/keystone/issues/8717 (Attempted to call `validateAndNormalizeDocument()` from the server).

As stated in https://github.com/keystonejs/keystone/pull/8403#issuecomment-1478851798 that made a workaround by adding `use client` clauses:

> The root cause of this is the crossover of React/Next code

In principle, this PR splits bunch of `.tsx` files into two separate ones. One for react-related (client-side) code and second one for platform-agnostic code. I am keeping the original file for backwards compatibility.
For example file:
`packages/fields-document/src/DocumentEditor/insert-menu.tsx`
has been split into:
`packages/fields-document/src/DocumentEditor/insert-menu-model.ts`
`packages/fields-document/src/DocumentEditor/insert-menu-view.tsx`
and the original file is now exporting above two:
```typescript 
export * from './insert-menu-model'
export * from './insert-menu-view'
```
External exports do not change, however internally, files that take part in validation process now import `-model.ts` files that are not importing disallowed hooks (`useState` etc).

There are no functional changes in the code apart from one in `packages/fields-document/src/DocumentEditor/utils-model.ts::insertNodesButReplaceIfSelectionIsAtEmptyParagraphOrHeading`. I will write about this one in the comment below.

It seems to work fine with my limited testing and all unit tests are passing. However I did not test this in some more advanced scenario and with custom components yet.

Please let me know whether this is something that you are willing to work on and eventually accept.

### CODE REVIEW

File: packages/fields-document/src/DocumentEditor/utils-model.ts [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+  Transforms.insertNodes(editor, nodes)
+  let path = pathRefForEmptyNodeAtCursor?.unref()
+  if (path) {
+    Transforms.removeNodes(editor, { at: path })
+    // even though the selection is in the right place after the removeNodes
+    // for some reason the editor blurs so we need to focus it again
+
+    // TODO: this causes 'TypeError: ([...].createContext) is not a function' in SSR
+    // not sure how to reproduce state in which this is neccessary
+    // ReactEditor.focus(editor)
```
Comment (marekryb) [inline packages/fields-document/src/DocumentEditor/utils-model.ts:93]: As stated in the description, this is the only functional change. Importing anything from `slate-react` causes
```

 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_3__.createContext) is not a function
    at eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/slate-react@0.102.0_react-dom@18.2.0_react@18.2.0_slate@0.102.0/node_modules/slate-react/dist/index.es.js:108:91)
    at (rsc)/../../node_modules/.pnpm/slate-react@0.102.0_react-dom@18.2.0_react@18.2.0_slate@0.102.0/node_modules/slate-react/dist/index.es.js (/home/exar/os/keystone/examples/framework-nextjs-app-directory/.next/server/vendor-chunks/slate-react@0.102.0_react-dom@18.2.0_react@18.2.0_slate@0.102.0.js:20:1)
```
because it uses `createContext`. I alleviated this problem in other place by having two versions of `createDocumentEditor`:  `packages/fields-document/src/DocumentEditor/editor-create-display.ts` and `packages/fields-document/src/DocumentEditor/editor-create-validation.ts`.

However in this case I am kind of clueless what the original problem was and how to workaround it.

File: examples/framework-nextjs-app-directory/package.json [hunk 2]
```diff
@@ -14,16 +14,16 @@
...
     "@keystone-6/document-renderer": "^1.1.0",
-    "@keystone-6/fields-document": "^8.0.0",
+    "@keystone-6/fields-document": "workspace:^",
     "@preconstruct/next": "^4.0.0",
     "@prisma/client": "^4.16.2",
     "graphql": "^16.8.1",
     "graphql-request": "^5.0.0",
     "graphql-yoga": "^3.1.0",
-    "next": "^13.3.0",
+    "next": "^13.4.9",
```
Comment (marekryb) [inline examples/framework-nextjs-app-directory/package.json:26]: `next:build` builds fine with latest `nextjs` (14.1.0), however `keystone:build` has some unrelated problem with >=14
```
Error: <Html> should not be imported outside of pages/_document.
```

**Comment by dcousens** [comment]
I am really open to accepting this work, my only concern is that we're trying to solve a number of problems in one pull request.
If we can break this into a few smaller pull requests, I can review and approve more quickly.

File: examples/framework-nextjs-app-directory/package.json (hunk 2 above)
Comment (dcousens) [reply examples/framework-nextjs-app-directory/package.json:26]: Can we break this out into it's own pull request, and why do we need to bump?

**Comment by dcousens** [comment]
Can you please put any code moving operations into their own commits, so I can easily review those commits and then focus only on the diff?

**Comment by marekryb** [comment]
> I am really open to accepting this work, my only concern is that we're trying to solve a number of problems in one pull request.
If we can break this into a few smaller pull requests, I can review and approve more quickly.

Unfortunately this is not possible. Everything here is related and do not function without other pieces.

> Can you please put any code moving operations into their own commits, so I can easily review those commits and then focus only on the diff?

This is already kind of the case. The initial ~18 "wip" labelled commits are splitting one file and then changing related imports in other places.

My workflow was like this:
1) remove existing 'use client' to trigger error
2) see the error when running `examples/framework-nextjs-app-directory`
3) split the file that has the error and fix imports related to it
4) run `pnpm jest packages/fields-document/`
5) `git commit -am "wip"`
6) goto 2 until working

File: examples/framework-nextjs-app-directory/package.json (hunk 2 above)
Comment (marekryb) [reply examples/framework-nextjs-app-directory/package.json:26]: There is no real reason for this change. Originally I wanted to put `^14.1.0` here, but because I cannot we can just leave it as it was.

**Comment by marekryb** [comment]
Removed all changes to `examples/framework-nextjs-app-directory`. Can be split to separate PR when this is done.

**Comment by dcousens** [comment]
@marekryb OK, if you can get everything into a working order, as atomic as reasonable, I could jump in towards the end

**Comment by dcousens** [comment]
I have updated this pull request and rebased each of the changes.
I effectively did the changes again from HEAD, to ensure I understood everything that was changed, but the credit and work will still be attributed to you @marekryb when merged.

Thanks again for this @marekryb, and I have the same conclusion, this may not resolve _every_ situation for now, but, we should be nearer to that with this pull request.

File: packages/fields-document/src/DocumentEditor/utils-model.ts (hunk 1 above)
Comment (dcousens) [reply packages/fields-document/src/DocumentEditor/utils-model.ts]: When did this happen for you?

Comment (dcousens) [reply packages/fields-document/src/DocumentEditor/utils-model.ts]: I have resolved this with b85894f, by using a dependency passing pattern to side-step the problem without duplicating the code.

Comment (dcousens) [reply packages/fields-document/src/DocumentEditor/utils-model.ts]: The problem @marekryb is that `ReactEditor` has a call to `createContext`, which isn't allowed on the server.
