### ISSUE TITLE
Missing module in `next/server/pages/api`

### ISSUE THREAD

**Issue by limegorilla** [keystonejs/keystone#7229]
Using a brand new project bootstrapped with `yarn create keystone app` trying to run using `yarn dev`

On boot of app, after the App UI is ready, this comes in:
```javascript
Error: Cannot find module '/Users/liamdoyle/Developer/theshoregroup/keystonecms/.keystone/admin/.next/server/pages/api/__keystone_api_build'
Require stack:
- /Users/liamdoyle/Developer/theshoregroup/keystonecms/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js
- /Users/liamdoyle/Developer/theshoregroup/keystonecms/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js
- /Users/liamdoyle/Developer/theshoregroup/keystonecms/node_modules/@keystone-6/core/bin/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/Users/liamdoyle/Developer/theshoregroup/keystonecms/node_modules/next/build/webpack/require-hook.ts:141:26)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at initKeystone (/Users/liamdoyle/Developer/theshoregroup/keystonecms/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js:223:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/liamdoyle/Developer/theshoregroup/keystonecms/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js',
    '/Users/liamdoyle/Developer/theshoregroup/keystonecms/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js',
    '/Users/liamdoyle/Developer/theshoregroup/keystonecms/node_modules/@keystone-6/core/bin/cli.js'
  ]
}
```

Isn't related to my dependancies - went down and up a 0.0.x version with no change. Also happened on the `Azure Example`

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/29333568/151177976-005e625b-334c-497b-b157-542b9a8f6897.png">

**Comment by bladey** [comment]
Hey @limegorilla, that's odd, here is what I get --

```
➜  temp nvm use 16.13
Now using node v16.13.2 (npm v8.1.2)
➜  temp which yarn
/Users/bladey/.nvm/versions/node/v16.13.2/bin/yarn
➜  temp yarn create keystone-app
yarn create v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-keystone-app@6.0.1" with binaries:
      - create-keystone-app
[#######################################################################################################################] 160/160
✨ You're about to generate a project using Keystone 6 packages.

✔ What directory should create-keystone-app generate your app into? · test-app

✔ Installed dependencies with yarn.

🎉  Keystone created a starter project in: test-app

  To launch your app, run:

  - cd test-app
  - yarn dev

  Next steps:

  - Read test-app/README.md for additional getting started details.
  - Edit test-app/keystone.ts to customize your app.
  - Open the Admin UI
  - Open the Graphql API
  - Read the docs
  - Star Keystone on GitHub

✨  Done in 36.84s.
➜  temp cd test-app
➜  test-app yarn postinstall
yarn run v1.22.17
$ keystone postinstall
✨ GraphQL and Prisma schemas are up to date
✨  Done in 1.63s.
➜  test-app yarn dev
yarn run v1.22.17
$ keystone dev
✨ Starting Keystone
⭐️ Dev Server Starting on http://localhost:3000
⭐️ GraphQL API Starting on http://localhost:3000/api/graphql
✨ Generating GraphQL and Prisma schemas
✨ sqlite database "keystone.db" created at file:./keystone.db
✨ Your database is now in sync with your schema. Done in 314ms
✨ Connecting to the database
✨ Creating server
✅ GraphQL API ready
✨ Generating Admin UI code
✨ Preparing Admin UI app
event - compiled client and server successfully in 2.6s (1207 modules)
✅ Admin UI ready
wait  - compiling /api/__keystone_api_build...
event - compiled client and server successfully in 217 ms (1225 modules)
```

I'll check in with the team and see if they have any ideas.

**Comment by limegorilla** [comment]
Weird - I've just noticed this has completely disappeared!

This wasn't isolated to my machine but I'm really not sure why/what caused it - nothing has changed since last week.

**Comment by udovichenko** [comment]
I have exactly the same issue while trying to install a fresh instance of keystone. MacOS, node v16.13.1

**Comment by dcousens** [comment]
Happy to re-open this if we can reproduce the problem

**Comment by nilskjQL** [comment]
Same error, doing exact same as above, worked last week but not now. MacOS, node 16.13.2, yarn 1.22.15:
```
 There was an error loading your Keystone config
Error: Cannot find module '/Users/nilskjellman/dev/ks/.keystone/admin/.next/server/pages/api/__keystone_api_build'
...
  code: 'MODULE_NOT_FOUND',
```

**Comment by rburgst** [comment]
I am getting this on a brand new generation

```
yarn create keystone-app
cd server
yarn dev

🚨 There was an error loading your Keystone config
Error: Cannot find module '/Users/user/git/server/.keystone/admin/.next/server/pages/api/__keystone_api_build'
Require stack:
- /Users/user/git/server//node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js
```

using node 16.14.2

```
node --version
v16.14.2
```

**Comment by rburgst** [comment]
I guess I will create a new issue as this one is closed

**Comment by rburgst** [comment]
see https://github.com/keystonejs/keystone/issues/7500

**Comment by uniquesolution29** [comment]
I got that error when I was using v16.13.0.
It works with another node versions like v16.16.0.
