### ISSUE TITLE
Keystone supports node 4.1.1?

### ISSUE THREAD

**Issue by claudiojulioferraz** [keystonejs/keystone#1707]
It works perfectly in 0.12.7 node but not in 4.1.1. I am trying to install Keystone with docker, but when I run `node keystone`, the error below:
```shell
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
/home/nodejs/retis/node_modules/keystone/lib/core/mount.js:316
				throw e;
				^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/nodejs/retis/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/nodejs/retis/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/nodejs/retis/node_modules/node-sass-middleware/middleware.js:1:74)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at mount (/home/nodejs/retis/node_modules/keystone/lib/core/mount.js:306:21)
    at start (/home/nodejs/retis/node_modules/keystone/lib/core/start.js:239:7)
    at Object.<anonymous> (/home/nodejs/retis/keystone.js:69:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by creynders** [comment]
When swapping to node v4 it's best to reinstall all dependencies. I.e. this should be solved by deleting your `node_modules` directory and running `npm install`.

**Comment by claudiojulioferraz** [comment]
I'm using docker with node image: latest, did not upgrade. Still I tried to do what you said, but does not. There are some pictures in "Docker Hub" of the "Keynote" already installed, but are all broken. Thank you!

Using Google Translate.

**Comment by creynders** [comment]
Ah, hadn't noticed you use docker. I don't have any experience with using KS on it, sorry.

**Comment by morenoh149** [comment]
@claudiojulioferraz make sure you have `node-sass` 3.3.2 or greater https://github.com/keystonejs/generator-keystone/commit/c74a13c6898558635083ff9b64b2a8baef1bb926 with node v4

**Comment by claudiojulioferraz** [comment]
Thank you!
