### ISSUE TITLE
Error using mutations/queries added with extendGraphQLSchema

### ISSUE THREAD

**Issue by ropaolle** [keystonejs/keystone#2541]
# Bug report

## Describe the bug

Calling mutations created with extendGraphQLSchema results in `this._executeOperation is not a function` error. I.e. when it is called it is undefined.

I can see that `@keystonejs/keystone": "^6.0.0` added a custom graphQl provider, so maybe I have to call something more then just keystone.extendGraphQLSchema.

## To Reproduce

Extend the schema and call a query or a mutation.

```js
keystone.extendGraphQLSchema({
  types: [],
  queries: [
    {
      schema: 'getUserByName(name: String!): Boolean',
      resolver: async (item, { name }, context, info, { query }) => {
        const {
          errors,
          data: { allUsers }
        } = await query(
          `query {
            allAllUsers(where: { name: "${name}"}) {
              id
            }
          }`
        );

        // Kaboom! - this._executeOperation is not a function

        return true;
      }
    }
  ],
  mutations: []
});
```

## System information

- OS: Windows
- KeystoneJS
    "@keystonejs/adapter-mongoose": "^5.2.1",
    "@keystonejs/app-admin-ui": "^5.9.2",
    "@keystonejs/app-graphql": "^5.1.2",
    "@keystonejs/app-next": "^5.1.1",
    "@keystonejs/auth-password": "^5.1.2",
    "@keystonejs/fields": "^7.0.0",
    "@keystonejs/keystone": "^6.0.1",
    "@keystonejs/list-plugins": "^5.1.2",

## Additional context

It was working with "@keystonejs/keystone": "^5.6.0".

**Comment by timleslie** [comment]
I just published new packages with a fix for this. Please let us know if there are any other issues!

**Comment by ropaolle** [comment]
Wow, that was quick. Now it works as expected. Thanks.
